### ISSUE TITLE
Links to tutorials broken…

### ISSUE THREAD

**Issue by meerestier** [loicdtx/bfastSpatial#60]
I would appreciate, if you updated the links in the readme…

**Comment by loicdtx** [comment]
The tutorial page should be back by now.

**Comment by meerestier** [comment]
Sorry, not for the readme.md

http://dutri001.github.io/bfastSpatial/
or
http://www.loicdutrieux.com/talks/SCERIN-2015-bfastSpatial/
respectively…

**Comment by loicdtx** [comment]
I see, I'll try to fix that. In the meantime you can use http://www.loicdutrieux.net/bfastSpatial/ and http://www.loicdutrieux.net/talks/SCERIN-2015-bfastSpatial/
