### ISSUE TITLE
Issue creating layer stack

### ISSUE THREAD

**Issue by velocity56** [loicdtx/bfastSpatial#63]
Hi,
I have been having issues using the timeStack function to generate a layer stack from a series of Landsat 8 rasters. These rasters were all pre-processed using the ProcessLandsatBatch function, and are all coming from the exact same year, path, and row. However, every time I try to generate the layer stack, I get this error message: "Error in compareRaster(rasters) : different extent". Any suggestions on how to solve this issue would be very appreciated! 

Thank you for your help!

**Comment by loicdtx** [comment]
Did you use an extent (`e=`) in `processLandsatBatch()`? We recommend to always use one to ensure that inputs to `timeStack()` all have the same extent. It's likely that full scenes even though they are from the same PR have slightly different extents.
