### ISSUE TITLE
bfmSpatial error

### ISSUE THREAD

**Issue by Lionv** [loicdtx/bfastSpatial#65]
I have a times series raster stack from MODIS mod13q1. covering a period of time of 4 years every 16 days. I run the script following the instructions in the webside http://www.loicdutrieux.net/bfastSpatial/ . 
When i want to plot the raster brick that result after running bfmspatial, the breakpoint and magnitude boxes are empty, however the error box is full. This mean that there is an error in the process. What can be the source of error?. I dont find information to figure this out.. The raster stack was created using  timeStackMODIS

**Comment by loicdtx** [comment]
Can you provide a little more information on what you did and what you have:
e.g.
- The exact `bfmSpatial()` command you ran
- The return of `getZ(x)` (`x` being your rasterStack/Brick)

There's a utility (`bfmPixel()`) to check that all parameters are working properly before running the algorithm on the entire raster object

**Comment by Lionv** [comment]
I list all files using
lst<-list.files(pattern="*.tif$")
I create a date object 
dates<-seq(as.Date("2010-01-01"),by=16,length=115)
I create a time stack object by
m<-timeStackMODIS(lst,dates,rm.na=T)
The return of the getZ(x) are 115 dates, starting "2013-01-01" until "2012-12-18".
The bfmstapial command
bfm <- bfmSpatial(x = m, start = 2010, formula = response ~ trend + harmon, order = 3)
I can perform the annual summary (it works well) by this command:
annualMed <- annualSummary(m, fun=median, na.rm=TRUE)
When i try to use the bfmpixel() utility, after plotting a subset of the stack, an error is shown
 plot (m,1)
> bfm3 <- bfmPixel(m,start=c(2010,1),dates=dates,interactive = T)
Error in xj[i, , drop = FALSE] : subscript out of bounds

**Comment by loicdtx** [comment]
`start=` corresponds to the start of the monitoring period, which needs to be preceded by a stable history period; therefore it cannot be the same as the beginning of your time series. There is no hard rule nor anything statistically proven but it's generally accepted that the stable history period should be at least 2 years longs in the case of 16 days modis data (see the original bfastmonitor paper by Verbesselt et al. 2012).

> Furthermore, we recommend limiting the disturbance detection to time series with a sufficiently stable history period to enable a reliable estimation of the 8 season-trend model parameters (Eq. 1), e.g., longer than 2 years in this study corresponding to 46 observations of 16-day data.

Also note that since you are working with 16 days modis data, you can set the `pptype=` argument to `16-days`

**Comment by loicdtx** [comment]
Also I doubt `dates <- seq(as.Date("2010-01-01"), by=16, length=115)` will give you the right time vector if you used modis 16 days composites produced by the USGS. They normally truncate the last composite of the year and re-start every year with a new composite.

**Comment by Lionv** [comment]
I change the monitoring period to 2012 and the problem was solved. Thanks a lot for your help!!!!
