### ISSUE TITLE
Error Extracting Brightness Temperature

### ISSUE THREAD

**Issue by fyousef** [loicdtx/bfastSpatial#82]
Hi there,

Thanks again for the wonderful package. I have encountered an error recently. I have bt_band6 downloaded from ESPA and wanted to extract it using the proccessLandsat function. However, I receive this error:
```
for (fls in mfiles) {
  processLandsat(x=fls, vi=c("ndvi", "bt_band6"), outdir = dirout, delete=TRUE, mask="pixel_qa", keep = c(66, 130), overwrite = TRUE, fileExt = "tif")
}
```

> Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘overlay’ for signature ‘"missing", "missing"’

I looked up the help page for processLandsat and apparently I should be able to process surface reflectance, but could not find any document for brightness temperature.  

FYI, I have used a variety of substitutes for "bt_band6" (e.g. band6, T1_bt_band6).

Thank you

**Comment by loicdtx** [comment]
What does the brightness temperature file name look like? Can you send an example?

**Comment by fyousef** [comment]
```
LT04_L1TP_014035_19821111_20161004_01_T1_bt_band6.tif
```

**Comment by loicdtx** [comment]
I pushed a quick fix to the develop branch, it should work now if you refer to the band as `band6`.
Let me know if it works.

**Comment by fyousef** [comment]
Thank you Loïc. It works great. 

Cheers
Foad
