### ISSUE TITLE
how to create a dataset like tura

### ISSUE THREAD

**Issue by notforscience** [loicdtx/bfastSpatial#83]
hi there! I'm very new to R language and bfast spatial. I want to create a RasterBrick like tura using MODIS data.
here is my code:
alist <- list.files(path="E:/Spatial", 
     pattern =".TIF$", full.names=TRUE)
s <- stack(alist)
s01<- getValues (s)
then i tried to use the 'getSceneinfo' function but failed.

**Comment by loicdtx** [comment]
Have a look at `timeStackMODIS`. You may have to override `getMODISinfo` depending on how your file names are formated

**Comment by notforscience** [comment]
I think the  timeStackMODIS function means: 
list your data files by "x <- list.files(x, pattern=pattern, full.names=TRUE)",
make a rasterstack by " s <- stack(x)"
since the x has a date vector, you can extract the time vector by " time <- getMODISinfo(x)$date"
finally can create a s dataset by "s <- setZ(x=s, z=time)"
my code is:
"test01 <- list.files(path="F:/modis data/01", pattern = "TIF$" , full.names = TRUE)
s <- raster::stack(test01)
time <- getMODISinfo(test01)"
![qq 20180320202001](https://user-images.githubusercontent.com/37509808/37654194-48b90c78-2c7c-11e8-9100-68d4de68a52b.png)
![qq 20180320202114](https://user-images.githubusercontent.com/37509808/37654207-4e34b26a-2c7c-11e8-820b-aa61321831b0.png)
could you please tell me where is wrong?
