### ISSUE TITLE
'mc.cores' > 1 is not supported on Windows

### ISSUE THREAD

**Issue by jgomezd** [loicdtx/bfastSpatial#92]
Do you know how can I use multiple cores on Windows?
I tried the following code:
t2 <- system.time(
  bfm <- bfmSpatial(tura, start=c(2009, 1), order=1, mc.cores=2)
)

However, I got the following error:
Error in mclapply(X = blocs, FUN = fun2, mc.cores = mc.cores) : 
  'mc.cores' > 1 is not supported on Windows
Timing stopped at: 0.03 0 0.03

R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Platform: x86_64-w64-mingw32/x64 (64-bit)

Windows 10
Intel Core i7 (4 cores)
12 GB Ram

**Comment by loicdtx** [comment]
It should work if you install the development version of the package.
`install_github('loicdtx/bfastSpatial', ref='develop')`
